import { ScheduleCreateRequest } from '@amadda/global-types';
import { ScheduleEditFormProps } from '../components/ScheduleEdit/formdata';

export const initFormValues: ScheduleEditFormProps = {
  startYear: '',
  startMonth: '',
  startDate: '',
  startTime: '',
  startMinute: '',
  endYear: '',
  endMonth: '',
  endDate: '',
  endTime: '',
  endMinute: '',
  category: [],
  scheduleName: '',
  participants: [],
  scheduleStartAt: '',
  scheduleEndAt: '',
  isDateSelected: false,
  isTimeSelected: false,
  isAllday: false,
  isAuthorizedAll: false,
  scheduleContent: '',
  alarmTime: '',
  categorySeq: '',
  scheduleMemo: '',
  partySearchInput: '',
  partySearchResult: [],
  categoryInput: '',
};

export const scheduleCreateRequestInit: ScheduleCreateRequest = {
  scheduleName: '',
  participants: [],
  scheduleStartAt: '',
  scheduleEndAt: '',
  isDateSelected: false,
  isTimeSelected: false,
  isAllday: false,
  isAuthorizedAll: false,
  scheduleContent: '',
  alarmTime: 'NONE',
  scheduleMemo: '',
};

export const refInputNames: Array<keyof ScheduleEditFormProps> = [
  'startYear',
  'startMonth',
  'startDate',
  'startTime',
  'startMinute',
  'endYear',
  'endMonth',
  'endDate',
  'endTime',
  'endMinute',
  'category',
  'scheduleName',
  'participants',
  'scheduleStartAt',
  'scheduleEndAt',
  'isDateSelected',
  'isTimeSelected',
  'isAllday',
  'isAuthorizedAll',
  'scheduleContent',
  'alarmTime',
  'categorySeq',
  'scheduleMemo',
  'partySearchInput',
  'partySearchResult',
  'categoryInput',
];
