import { ScheduleEditFormProps } from '../formdata';

export const refInputNames: Array<keyof ScheduleEditFormProps> = [
  'startYear',
  'startMonth',
  'startDate',
  'startTime',
  'startMinute',
  'endYear',
  'endMonth',
  'endDate',
  'endTime',
  'endMinute',
  'category',
  'scheduleName',
  'participants',
  'scheduleStartAt',
  'scheduleEndAt',
  'isDateSelected',
  'isTimeSelected',
  'isAllday',
  // 'isAuthorizedAll',
  'scheduleContent',
  'alarmTime',
  'categorySeq',
  'scheduleMemo',
  'partySearchInput',
  'partySearchResult',
  'categoryInput',
];
